# Generated by Django 5.0.4 on 2024-04-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userType', models.CharField(max_length=20)),
                ('userFname', models.CharField(max_length=100)),
                ('userLname', models.CharField(max_length=100)),
                ('userEmail', models.EmailField(max_length=254, unique=True)),
                ('userPassword', models.CharField(max_length=100)),
            ],
        ),
    ]
