# Generated by Django 5.0.4 on 2024-04-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_Student',
        ),
    ]
