# Generated by Django 5.0.4 on 2024-04-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_rename_user_user_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('checkoutDate', models.DateField(blank=True, null=True)),
                ('bookForLater', models.DateField(blank=True, null=True)),
                ('bookingReturnDate', models.DateField(blank=True, null=True)),
                ('bookingReturnStatus', models.CharField(max_length=20, null=True)),
                ('bookingReason', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='User_Student',
            new_name='User',
        ),
        migrations.CreateModel(
            name='User_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='user_booking',
            constraint=models.UniqueConstraint(fields=('user', 'booking'), name='unique_user_booking'),
        ),
    ]
