# Generated by Django 5.0.4 on 2024-04-21 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_booking_rename_user_student_user_user_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminFname', models.CharField(max_length=100)),
                ('adminLname', models.CharField(max_length=100)),
                ('adminEmail', models.EmailField(max_length=254, unique=True)),
                ('adminPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('productType', models.CharField(max_length=500)),
                ('productQuantity', models.IntegerField()),
                ('productAudit', models.DateField()),
                ('productLocation', models.CharField(max_length=100)),
                ('productStatus', models.CharField(max_length=50, null=True)),
                ('productComments', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportId', models.AutoField(primary_key=True, serialize=False)),
                ('reportType', models.CharField(max_length=50)),
                ('reportDate', models.DateField(auto_now_add=True)),
                ('reportContent', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.user')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Details',
            fields=[
                ('deviceId', models.AutoField(primary_key=True, serialize=False)),
                ('deviceType', models.CharField(max_length=100)),
                ('deviceSerial', models.CharField(max_length=20)),
                ('deviceCPU', models.CharField(max_length=20)),
                ('deviceGPU', models.CharField(max_length=20)),
                ('deviceRam', models.CharField(max_length=10)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.report')),
            ],
        ),
        migrations.CreateModel(
            name='Admin_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.admin')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.report')),
            ],
        ),
        migrations.AddConstraint(
            model_name='product_booking',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_product_booking'),
        ),
        migrations.AddConstraint(
            model_name='product_report',
            constraint=models.UniqueConstraint(fields=('product', 'report'), name='unique_product_report'),
        ),
        migrations.AddConstraint(
            model_name='admin_report',
            constraint=models.UniqueConstraint(fields=('admin', 'report'), name='unique_admin_report'),
        ),
    ]
