# Generated by Django 5.0.4 on 2024-04-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_admin_product_report_product_booking_product_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productComments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='productStatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
