# Generated by Django 5.0.4 on 2024-04-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_alter_product_productcomments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_details',
            name='deviceName',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
