# Generated by Django 5.0.4 on 2024-04-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_product_details_devicename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_details',
            name='deviceCPU',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='deviceGPU',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='deviceRam',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
