# Generated by Django 5.0.3 on 2024-04-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_alter_product_details_devicecpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appone.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='productStatus',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=50, null=True),
        ),
    ]
