# Generated by Django 5.0.3 on 2024-04-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0008_booking_product_alter_product_productstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productStatus',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=50, null=True),
        ),
    ]
