# Generated by Django 5.0.3 on 2024-04-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0009_alter_product_productstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bookingReturnDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='checkoutDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
