# Generated by Django 5.0.3 on 2024-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0011_category_booking_bookingstatus_alter_user_usertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingstatus',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True),
        ),
    ]
