# Generated by Django 5.0.3 on 2024-04-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0012_alter_booking_bookingstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookForLater',
            field=models.DateField(blank=True, default='None', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingReturnStatus',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
    ]
