# Generated by Django 5.0.3 on 2024-04-27 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0013_alter_booking_bookforlater_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookForLater',
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='appone.user'),
        ),
    ]
