# Generated by Django 5.0.3 on 2024-04-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0016_rename_user_customuser_alter_usertype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productStatus',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('On Repair', 'On Repair'), ('Damaged', 'Damaged')], default='pending', max_length=50, null=True),
        ),
    ]
