# Generated by Django 4.2.3 on 2024-05-02 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0017_alter_product_productstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reportContent',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reportDate',
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='products',
            field=models.ManyToManyField(to='appone.product'),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='reportType',
            field=models.CharField(blank=True, choices=[('inventoryStatus', 'Inventory Status'), ('equipmentUsageHistory', 'Equipment Usage History'), ('overdueEquipment', 'Overdue Equipment')], max_length=100, null=True),
        ),
    ]
